

sources:
  dropbox:
    dir: '/Users/ajo/Dropbox/Camera Upload'
  nasinbox:
    dir: '/mnt/nas/Pictures/inbox'


output_dir: '/mnt/nas/Pictures'
duplicates_dir: 'duplicates'
log_file: 'photosort.log'
db_file: 'photosort.db'

dir_pattern: "%(year)d/%(year)d_%(month)d_%(day)d"
